version: '2.1'

services:
  build:
    build:
      context: ..
      dockerfile: docker-build/Dockerfile
    volumes:
      - ..:/usr/src/app/cassandra-reaper
      - ../packages:/usr/src/app/packages
